;(function(){

'use strict';

angular.module('SymfonyAppTpl', []).run(['$templateCache', function($templateCache) {

  $templateCache.put('article.html', '<div class="section section-jobs"><div class="container"><div class="row"><div class="col-xs-12"><h2 class="pull-left"><strong>[[ article.title ]]</strong></h2><div class="pull-right" style="font-size: 30px;">[[ article.rating ]]<uib-rating class="text-success" ng-model="article.rating" max="max" read-only="true" aria-labelledby="default-rating"></uib-rating></div></div></div><div class="row"><div class="col-xs-12"><div class="clearfix"><p>[[ article.excerpt ]]</p><hr><p>[[ article.body ]]</p><br><div class="test" ng-show="article.answers"><div class="clearfix"><div class="pull-left"><h3>Answers ([[ article.answers.length ]])</h3></div><div class="pull-right"><a style="position:relative; left: inherit; margin-left: 0" class="job-cta-link btn btn-lg btn-primary btn-success btn-block" href="#" onclick="return false" ng-click="postAnswer(article.id)">Post an Answer</a></div></div><hr><div ng-repeat="answer in article.answers" style="margin-bottom: 15px">[[ answer.body ]]<div>By [[ answer.name ]] on [[ answer.hr_date ]]</div></div></div></div></div></div></div></div>');

  $templateCache.put('article_list.html', '<div class="section section-jobs"><div class="container"><div class="row"><div class="col-xs-12 col-md-10 col-md-offset-1"><h2 style="text-align: center;"><strong>Articles</strong></h2></div></div><br><br><div class="row" ng-repeat="article in articles"><div class="col-xs-12 job-section"><div class="row"><div class="job-wrap match-height"><h4 class="job-title">[[ article.title ]]</h4><p>[[ article.excerpt ]]</p><p>&nbsp;</p><hr><div class="clearfix"><div class="pull-left">[[ article.rating ]] <i class="glyphicon glyphicon-star"></i></div><div class="pull-right" ng-show="article.no_answers"><span class="fa fa-comment"></span> [[ article.no_answers ]]</div><a class="job-cta-link btn btn-lg btn-primary btn-block" href="#" onclick="return false" ng-click="viewArticle(article.id)">View article</a></div></div></div></div></div></div></div>');

  $templateCache.put('createAnswer.html', '<div class="modal-header"><h3 class="modal-title">Post an answer</h3></div><form name="userForm" ng-submit="submitAnswer()" novalidate><div class="modal-body"><div class="form-group" ng-class="{\'has-error\' : !user.name && !userForm.name.$pristine}"><label>Name</label> <input type="text" name="name" ng-model="user.name" class="form-control"></div><div class="form-group" ng-class="{\'has-error\' : !user.answer && !userForm.answer.$pristine}"><label>Answer</label><br><textarea name="answer" ng-model="user.answer" rows="6" cols="60" class="form-control">\n        </textarea></div><div class="form-group" ng-class="{\'has-error\' : !user.rating && !userForm.rating.$pristine}"><label>Rating</label><br><uib-rating class="text-warning" style="font-size: 30px" ng-model="user.rating" on-leave="overStar = null" titles="[\'one\',\'two\',\'three\']" aria-labelledby="default-rating"></uib-rating></div></div><div class="modal-footer"><button class="btn btn-warning" ng-click="cancel()">Cancel</button> <input type="submit" class="btn btn-primary" value="Submit" ng-disabled="! user.name || ! user.answer || !user.rating"></div></form>');

  $templateCache.put('createArticle.html', '<div class="modal-header"><h3 class="modal-title">Create New Article</h3></div><form name="userForm" ng-submit="submitArticle()" novalidate><div class="modal-body"><div class="form-group" ng-class="{\'has-error\' : !article.title && !userForm.title.$pristine}"><label>Title</label> <input type="text" name="title" ng-model="article.title" class="form-control"></div><div class="form-group" ng-class="{\'has-error\' : !article.excerpt && !userForm.excerpt.$pristine}"><label>Excerpt</label><br><textarea name="excerpt" ng-model="article.excerpt" rows="4" cols="60" class="form-control">\n        </textarea></div><div class="form-group" ng-class="{\'has-error\' : !article.body && !userForm.body.$pristine}"><label>Body</label><br><textarea name="body" ng-model="article.body" rows="10" cols="60" class="form-control">\n        </textarea></div></div><div class="modal-footer"><button class="btn btn-warning" ng-click="cancel()">Cancel</button> <input type="submit" class="btn btn-primary" value="Submit" ng-disabled="! article.title || ! article.excerpt || !article.body"></div></form>');

  $templateCache.put('login.html', '<div class="modal-header"><h3 class="modal-title">Login</h3></div><form name="userForm" ng-submit="submitLogin()" novalidate><div class="modal-body"><div class="form-group" ng-class="{\'has-error\' : !user.username && !userForm.username.$pristine}"><label>Username</label> <input type="text" name="username" ng-model="user.username" class="form-control"></div><div class="form-group" ng-class="{\'has-error\' : !user.password && !userForm.password.$pristine}"><label>Username</label> <input type="password" name="password" ng-model="user.password" class="form-control"></div></div><div class="modal-footer"><button class="btn btn-warning" ng-click="cancel()">Cancel</button> <input type="submit" class="btn btn-primary" value="Submit" ng-disabled="! user.username || ! user.password"></div></form>');

}]);

})();