<?php

namespace ApiBundle\Repository;

/**
 * ArticleRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
